name: Lint Code
on: push

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint Code
        run: yarn lint
